export const icons = {
  detail: require('./detail.svg').default,
  menu: require('./menu.svg').default,
  git: require('./git.svg').default,
  email: require('./mail.svg').default,
  linkedin: require('./linkedin.svg').default,
  whatsapp: require('./wh.svg').default,
  code: require('./code.svg').default,
  manutence: require('./manutence.svg').default,
  smartphone: require('./smartphone.svg').default,
  api: require('./api.svg').default,
  html: require('./html.svg').default,
  css: require('./css.svg').default,
  ts: require('./ts.svg').default,
  tailwind: require('./tailwind.svg').default,
  react: require('./react.svg').default,
  next: require('./next.svg').default,
};
